# Generated by Django 3.2.25 on 2025-04-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_advisor_organisation_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
