# Generated by Django 3.2.25 on 2025-05-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_option_question_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='source_file',
            field=models.FileField(blank=True, default=12, upload_to='quiz_files/'),
            preserve_default=False,
        ),
    ]
