# Generated by Django 3.2.25 on 2025-05-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_quiz_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='ecrypted_src_file',
            field=models.FileField(blank=True, null=True, upload_to='quiz_files/encrypted/'),
        ),
    ]
