# Generated by Django 3.2.25 on 2025-05-13 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_quiz_ecrypted_src_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(default=datetime.datetime(2025, 5, 13, 10, 16, 7, 162613, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='mark',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
