# Generated by Django 3.2.25 on 2025-05-19 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20250519_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='users.questions'),
        ),
    ]
