# Generated by Django 3.2.25 on 2025-05-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20250519_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='users.questions'),
        ),
        
    ]
