# Generated by Django 3.2.25 on 2025-05-19 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20250519_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='resource',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resource_questions', to='users.resource'),
            preserve_default=False,
        ),
    ]
