# Generated by Django 3.2.25 on 2025-05-19 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_questions_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='topic',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='users.question'),
        ),
        
    ]
