# Generated by Django 3.2.25 on 2025-05-19 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20250519_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
