# Generated by Django 3.2.25 on 2025-05-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
