# Generated by Django 3.2.25 on 2025-05-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_myquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myquestions',
            name='ended_at',
            field=models.DateTimeField(default=None),
        ),
    ]
