# Generated by Django 3.2.25 on 2025-05-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_myquestions_ended_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myquestions',
            name='ended_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
