# Generated by Django 3.2.25 on 2025-05-26 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_myquestions_ended_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyQuestionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('my_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='users.myquestions')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('marks', models.IntegerField(default=0)),
                ('answer', models.TextField()),
                ('expected_length', models.IntegerField(default=0)),
                ('actual_length', models.IntegerField(default=0)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('llm_evaluation_score', models.IntegerField(default=0)),
                ('final_score', models.IntegerField(default=0)),
                ('justification', models.TextField(blank=True, null=True)),
                ('missing_elements', models.TextField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('my_question_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='users.myquestionsubmission')),
            ],
        ),
    ]
