# Generated by Django 3.2.25 on 2025-05-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_myquestionsubmission_submissionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='level',
            field=models.CharField(default='Hard', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='mark',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='topic',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
