# Generated by Django 3.2.25 on 2025-05-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20250530_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='mark',
            field=models.IntegerField(blank=True),
        ),
    ]
