# Generated by Django 3.2.25 on 2025-05-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_resource_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
